### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [WatercressStudios/website#13]
It has been noticed that while using SamKirkland/FTP-Deploy-Action@3.1.1 your ftp-password x3YudDsjPC is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by Happiness-plus** [comment]
Yeah, that pipeline isn’t being used for production atm so it’s not a concern. 
Thank you for the heads up.
