### ISSUE TITLE
Character Bios Text Readability

### ISSUE THREAD

**Issue by TheForeverLoneWolf** [WatercressStudios/website#35]
Text on the Character Bio page should have a background to it for readability. In the image below, you can see the stars get in the way of the white text. Likely, just include a white background just like you do for the character cards.

https://puu.sh/Im3Qf/a204110231.png

**Comment by TheForeverLoneWolf** [comment]
NOTE: If you make the code, I can inject it where needed into the bio pages.

**Comment by Happiness-plus** [comment]
Done.
